### ISSUE TITLE
SW_DIP_x4_W7.62mm_Slide_Copal_CHS-B.kicad_mod missing F.Paste layer

### ISSUE THREAD

**Issue by sheffieldnikki** [KiCad/Buttons_Switches_SMD.pretty#24]
All the pads in this footprint are missing a tick in the 'F.Paste' layer. I haven't checked any of the other switch footprints to see if they have the same problem.

**Comment by evanshultz** [comment]
@sheffieldnick 
Thanks for reporting this. I looked at a few other footprints in this library and I didn't find F.Paste on any pads for Copal parts but I did for other footprints. Are you willing to fix these footprints and submit a PR?

Thanks again for noticing this issue and pointing it out here.

**Comment by sheffieldnikki** [comment]
On 02/09/2017 14:13, evanshultz wrote:
> @sheffieldnick <https://github.com/sheffieldnick>
> Thanks for reporting this. I looked at a few other footprints in this
> library and I didn't find F.Paste on any pads for Copal parts but I did
> for other footprints. Are you willing to fix these footprints and submit
> a PR?

Sorry, no.

**Comment by ghost** [comment]
I've opened a PR to fix this: https://github.com/KiCad/Buttons_Switches_SMD.pretty/pull/25
